### ISSUE TITLE
ゲーム開始直後左上に行くとボスステージに行く

### ISSUE THREAD

**Issue by potiii** [Cugry/Syachiku-Shooting#1]
ゲーム開始直後左上に行くとボスステージに行きます。修正お願いします。

**Comment by jt2jt2** [comment]
私の環境でも同様の現象がみられますが、デバッグ用の機能で開発者が残しているものだとおもうので急いで対応する必要はないと思います。

**Comment by Cugry** [comment]
It is a shortcut for debugging. I'll delete it by the stable release.
